<?php

declare(strict_types=1);

return [
    'roles' => [
        'admin' => ['*'],
        'control' => [
            'portal.access',
            'placement.board.view',
            'placement.application.transition',
            'placement.application.correct',
            'placement.records.view',
            'placement.records.manage',
            'placement.reports.view',
            'placement.import.manage',
            'placement.notifications.view',
            'placement.notifications.manage',
            'placement.preferences.view',
            'placement.preferences.manage',
            'placement.wanted.view',
            'placement.wanted.manage',
            'placement.system.view',
            'placement.sensitive.view',
            'placement.accommodation.view',
            'placement.cross_company.view',
            'advising.appointments.view',
            'advising.appointments.manage',
            'advising.notes.manage',
            'advising.tasks.manage',
        ],
        'placement' => [
            'portal.access',
            'placement.board.view',
            'placement.application.transition',
            'placement.application.correct',
            'placement.records.view',
            'placement.records.manage',
            'placement.reports.view',
            'placement.import.manage',
            'placement.import.rollback',
            'placement.notifications.view',
            'placement.notifications.manage',
            'placement.preferences.view',
            'placement.preferences.manage',
            'placement.wanted.view',
            'placement.wanted.manage',
            'placement.system.view',
            'placement.sensitive.view',
            'placement.accommodation.view',
            'placement.cross_company.view',
            'advising.appointments.view',
            'advising.appointments.manage',
            'advising.notes.manage',
            'advising.tasks.manage',
        ],
        'company' => [
            'portal.access',
            'placement.board.view',
            'placement.application.transition',
            'placement.application.correct',
            'placement.notifications.view',
            'placement.notifications.manage',
        ],
        'mobile' => [
            'portal.access',
            'placement.board.view',
            'placement.application.transition',
            'placement.notifications.view',
            'placement.notifications.manage',
            'placement.accommodation.view',
            'placement.cross_company.view',
            'placement.wanted.view',
            'placement.wanted.manage',
        ],
        'floor' => [
            'portal.access',
            'placement.board.view',
            'placement.application.transition',
            'placement.notifications.view',
            'placement.notifications.manage',
            'placement.accommodation.view',
            'placement.cross_company.view',
            'placement.wanted.view',
            'placement.wanted.manage',
        ],
        'auditor' => [
            'portal.access',
            'placement.board.view',
            'placement.records.view',
            'placement.reports.view',
            'placement.notifications.view',
            'placement.preferences.view',
            'placement.wanted.view',
            'placement.system.view',
            'placement.sensitive.view',
            'placement.accommodation.view',
            'placement.cross_company.view',
        ],
        'advisor' => [
            'portal.access',
            'advising.appointments.view',
            'advising.appointments.manage',
            'advising.notes.manage',
            'advising.tasks.manage',
        ],
    ],
];
