<?php

return [
    'default' => [
        'name' => 'Default Placement Day Workflow',
        'statuses' => [
            'idle' => ['label' => 'Idle', 'order' => 0, 'color' => '#eef0f2'],
            'scheduled' => ['label' => 'Scheduled', 'order' => 1, 'color' => '#fff4bf'],
            'intransit' => ['label' => 'In Transit', 'order' => 2, 'color' => '#ffe2a8'],
            'arrived' => ['label' => 'Arrived', 'order' => 3, 'color' => '#ffd0a6'],
            'requested' => ['label' => 'Requested', 'order' => 4, 'color' => '#e5f4a5'],
            'sendin' => ['label' => 'Send In', 'order' => 5, 'color' => '#bff0b9'],
            'inside' => ['label' => 'Inside', 'order' => 6, 'color' => '#bce9e4'],
            'exit' => ['label' => 'Exited', 'order' => 7, 'color' => '#ffd0d0'],
            'requestaway' => ['label' => 'Request Away', 'order' => 8, 'color' => '#cfefff'],
            'sendaway' => ['label' => 'Send Away', 'order' => 9, 'color' => '#e3d4ff'],
            'sent' => ['label' => 'Sent', 'order' => 10, 'color' => '#ffc9df'],
            'placed' => ['label' => 'Placed', 'order' => 11, 'color' => '#d9dde2'],
        ],
        'transitions' => [
            'idle' => ['scheduled' => ['control', 'admin']],
            'scheduled' => ['intransit' => ['company', 'mobile', 'control', 'admin']],
            'intransit' => ['arrived' => ['company', 'floor', 'control', 'admin']],
            'arrived' => ['requested' => ['company', 'control', 'admin']],
            'requested' => ['sendin' => ['control', 'placement', 'admin']],
            'sendin' => ['inside' => ['company', 'control', 'admin']],
            'inside' => ['exit' => ['company', 'control', 'admin']],
            'exit' => ['requestaway' => ['company', 'control', 'admin']],
            'requestaway' => ['sendaway' => ['control', 'placement', 'admin']],
            'sendaway' => ['sent' => ['company', 'control', 'admin']],
            'sent' => ['placed' => ['control', 'placement', 'admin']],
        ],
    ],
    'engineering_multi_branch' => [
        'name' => 'Engineering Multi-Branch Workflow',
        'statuses' => [
            'idle' => ['label' => 'Not Active', 'order' => 0, 'color' => '#eef0f2'],
            'eligible' => ['label' => 'Eligible', 'order' => 1, 'color' => '#e6f0ff'],
            'test' => ['label' => 'Online Test', 'order' => 2, 'color' => '#fff4bf'],
            'technical' => ['label' => 'Technical Round', 'order' => 3, 'color' => '#ffd0a6'],
            'hr' => ['label' => 'HR Round', 'order' => 4, 'color' => '#bce9e4'],
            'offer' => ['label' => 'Offer Released', 'order' => 5, 'color' => '#bff0b9'],
            'placed' => ['label' => 'Placed', 'order' => 6, 'color' => '#d9dde2'],
        ],
        'transitions' => [
            'idle' => ['eligible' => ['control', 'placement', 'admin']],
            'eligible' => ['test' => ['control', 'company', 'admin']],
            'test' => ['technical' => ['company', 'control', 'admin']],
            'technical' => ['hr' => ['company', 'control', 'admin']],
            'hr' => ['offer' => ['company', 'placement', 'admin']],
            'offer' => ['placed' => ['control', 'placement', 'admin']],
        ],
    ],
    'internship_season' => [
        'name' => 'Internship Season Workflow',
        'statuses' => [
            'idle' => ['label' => 'Not Active', 'order' => 0, 'color' => '#eef0f2'],
            'applied' => ['label' => 'Applied', 'order' => 1, 'color' => '#e6f0ff'],
            'shortlisted' => ['label' => 'Shortlisted', 'order' => 2, 'color' => '#fff4bf'],
            'interview' => ['label' => 'Interview', 'order' => 3, 'color' => '#ffd0a6'],
            'selected' => ['label' => 'Selected', 'order' => 4, 'color' => '#bff0b9'],
            'accepted' => ['label' => 'Accepted', 'order' => 5, 'color' => '#d9dde2'],
        ],
        'transitions' => [
            'idle' => ['applied' => ['control', 'placement', 'admin']],
            'applied' => ['shortlisted' => ['company', 'control', 'admin']],
            'shortlisted' => ['interview' => ['company', 'control', 'admin']],
            'interview' => ['selected' => ['company', 'placement', 'admin']],
            'selected' => ['accepted' => ['control', 'placement', 'admin']],
        ],
    ],
    'simple_placement_cell' => [
        'name' => 'Simple Placement Cell Workflow',
        'statuses' => [
            'idle' => ['label' => 'Not Active', 'order' => 0, 'color' => '#eef0f2'],
            'shortlisted' => ['label' => 'Shortlisted', 'order' => 1, 'color' => '#fff4bf'],
            'interview' => ['label' => 'Interview', 'order' => 2, 'color' => '#ffd0a6'],
            'offer' => ['label' => 'Offer', 'order' => 3, 'color' => '#bff0b9'],
            'placed' => ['label' => 'Placed', 'order' => 4, 'color' => '#d9dde2'],
        ],
        'transitions' => [
            'idle' => ['shortlisted' => ['control', 'placement', 'admin']],
            'shortlisted' => ['interview' => ['company', 'control', 'admin']],
            'interview' => ['offer' => ['company', 'placement', 'admin']],
            'offer' => ['placed' => ['control', 'placement', 'admin']],
        ],
    ],
    'pooled_campus_drive' => [
        'name' => 'Pooled Campus Drive Workflow',
        'statuses' => [
            'idle' => ['label' => 'Not Active', 'order' => 0, 'color' => '#eef0f2'],
            'registered' => ['label' => 'Registered', 'order' => 1, 'color' => '#e6f0ff'],
            'checked_in' => ['label' => 'Checked In', 'order' => 2, 'color' => '#fff4bf'],
            'screening' => ['label' => 'Screening', 'order' => 3, 'color' => '#ffe2a8'],
            'interview' => ['label' => 'Interview', 'order' => 4, 'color' => '#bce9e4'],
            'selected' => ['label' => 'Selected', 'order' => 5, 'color' => '#bff0b9'],
            'placed' => ['label' => 'Placed', 'order' => 6, 'color' => '#d9dde2'],
        ],
        'transitions' => [
            'idle' => ['registered' => ['control', 'placement', 'admin']],
            'registered' => ['checked_in' => ['floor', 'mobile', 'control', 'admin']],
            'checked_in' => ['screening' => ['company', 'control', 'admin']],
            'screening' => ['interview' => ['company', 'control', 'admin']],
            'interview' => ['selected' => ['company', 'placement', 'admin']],
            'selected' => ['placed' => ['control', 'placement', 'admin']],
        ],
    ],
    'virtual_interview_process' => [
        'name' => 'Virtual Interview Process Workflow',
        'statuses' => [
            'idle' => ['label' => 'Not Active', 'order' => 0, 'color' => '#eef0f2'],
            'invited' => ['label' => 'Invited', 'order' => 1, 'color' => '#e6f0ff'],
            'link_sent' => ['label' => 'Link Sent', 'order' => 2, 'color' => '#fff4bf'],
            'waiting' => ['label' => 'Waiting Room', 'order' => 3, 'color' => '#ffe2a8'],
            'in_interview' => ['label' => 'In Interview', 'order' => 4, 'color' => '#bce9e4'],
            'feedback' => ['label' => 'Feedback Pending', 'order' => 5, 'color' => '#ffd0a6'],
            'offer' => ['label' => 'Offer', 'order' => 6, 'color' => '#bff0b9'],
            'placed' => ['label' => 'Placed', 'order' => 7, 'color' => '#d9dde2'],
        ],
        'transitions' => [
            'idle' => ['invited' => ['control', 'placement', 'admin']],
            'invited' => ['link_sent' => ['control', 'placement', 'admin']],
            'link_sent' => ['waiting' => ['mobile', 'control', 'admin']],
            'waiting' => ['in_interview' => ['company', 'control', 'admin']],
            'in_interview' => ['feedback' => ['company', 'control', 'admin']],
            'feedback' => ['offer' => ['company', 'placement', 'admin']],
            'offer' => ['placed' => ['control', 'placement', 'admin']],
        ],
    ],
    'walk_in_job_fair' => [
        'name' => 'Walk-In Or Job-Fair Workflow',
        'statuses' => [
            'idle' => ['label' => 'Not Active', 'order' => 0, 'color' => '#eef0f2'],
            'registered' => ['label' => 'Registered', 'order' => 1, 'color' => '#e6f0ff'],
            'screened' => ['label' => 'Screened', 'order' => 2, 'color' => '#fff4bf'],
            'waiting' => ['label' => 'Waiting', 'order' => 3, 'color' => '#ffe2a8'],
            'interview' => ['label' => 'Interview', 'order' => 4, 'color' => '#bce9e4'],
            'offer' => ['label' => 'Offer', 'order' => 5, 'color' => '#bff0b9'],
            'placed' => ['label' => 'Placed', 'order' => 6, 'color' => '#d9dde2'],
        ],
        'transitions' => [
            'idle' => ['registered' => ['control', 'placement', 'admin']],
            'registered' => ['screened' => ['floor', 'control', 'admin']],
            'screened' => ['waiting' => ['floor', 'mobile', 'control', 'admin']],
            'waiting' => ['interview' => ['company', 'control', 'admin']],
            'interview' => ['offer' => ['company', 'placement', 'admin']],
            'offer' => ['placed' => ['control', 'placement', 'admin']],
        ],
    ],
];
