import type {
  Application,
  Candidate,
  Company,
  CompanyId,
  DemoSession,
  GuidedStep,
  RoleId,
} from "./types";

export const roleOrder: RoleId[] = [
  "control",
  "mobile",
  "floor",
  "company",
  "placement",
  "auditor",
];

export const roleConfig: Record<
  RoleId,
  {
    label: string;
    shortLabel: string;
    actor: string;
    summary: string;
    visibility: string[];
  }
> = {
  control: {
    label: "Control room",
    shortLabel: "Control",
    actor: "Control room",
    summary: "Coordinate every company, clash, and handover.",
    visibility: ["All candidate journeys", "Cross-company schedules", "Private operational context"],
  },
  mobile: {
    label: "Mobile tracker",
    shortLabel: "Mobile",
    actor: "Mobile tracker",
    summary: "Track candidates between campus locations.",
    visibility: ["Scheduled journeys", "Candidate location", "Accommodation logistics"],
  },
  floor: {
    label: "Floor coordinator",
    shortLabel: "Floor",
    actor: "Floor coordinator",
    summary: "Confirm arrivals and keep interview rooms moving.",
    visibility: ["Floor arrivals", "Interview rooms", "Accommodation logistics"],
  },
  company: {
    label: "Company tracker",
    shortLabel: "Company",
    actor: "Company tracker",
    summary: "Run one company process without seeing another company’s data.",
    visibility: ["Scoped company queue", "Interview readiness", "No cross-company private context"],
  },
  placement: {
    label: "Placement office",
    shortLabel: "Placement",
    actor: "Placement office",
    summary: "Coordinate handoffs, candidate choices, and placement outcomes.",
    visibility: ["Competing opportunities", "Candidate preferences", "Placement decisions"],
  },
  auditor: {
    label: "Auditor",
    shortLabel: "Auditor",
    actor: "Auditor",
    summary: "Review the complete history without changing it.",
    visibility: ["Complete activity trail", "Role and time of every update", "Read-only controls"],
  },
};

export const guidedSteps: GuidedStep[] = [
  {
    id: "resolve-clash",
    role: "control",
    act: 1,
    actionLabel: "Move Nova to 11:50",
    title: "Protect both interviews",
    instruction: "Dev cannot safely attend Atlas at 11:15 and Nova at 11:20. Move Nova to the safe slot.",
    benefit: "Both job opportunities stay open.",
    completion: "The scheduling clash is resolved. Dev can attend both interviews.",
  },
  {
    id: "start-transit-atlas",
    role: "mobile",
    act: 2,
    actionLabel: "Mark Dev en route to Atlas",
    title: "Get Dev moving",
    instruction: "Confirm that Dev has left the academic block for Atlas Systems.",
    benefit: "The floor team can prepare for his arrival.",
    completion: "Dev is now in transit to Atlas Systems.",
  },
  {
    id: "arrive-atlas",
    role: "floor",
    act: 2,
    actionLabel: "Confirm Dev has arrived",
    title: "Secure the Atlas interview",
    instruction: "Confirm Dev at Atlas reception before the 11:15 interview.",
    benefit: "Atlas can request him without delay.",
    completion: "Dev has arrived at Atlas Systems.",
  },
  {
    id: "request-atlas",
    role: "company",
    companyScope: "atlas",
    act: 3,
    actionLabel: "Request Dev for interview",
    title: "Call Dev into Atlas",
    instruction: "Atlas is ready. Request Dev from the floor queue.",
    benefit: "The placement office can approve the interview handoff.",
    completion: "Atlas Systems has requested Dev.",
  },
  {
    id: "approve-atlas",
    role: "placement",
    act: 3,
    actionLabel: "Approve handoff to Atlas",
    title: "Send Dev into Atlas",
    instruction: "Coordinate the request and release Dev to the interview room.",
    benefit: "Dev reaches his first protected opportunity.",
    completion: "Dev is ready to interview with Atlas Systems.",
  },
  {
    id: "run-atlas-interview",
    role: "company",
    companyScope: "atlas",
    act: 3,
    actionLabel: "Record Atlas interview complete",
    title: "Complete the first interview",
    instruction: "Confirm the interview is complete and request Dev’s next handoff.",
    benefit: "Dev finishes Atlas without losing the Nova slot.",
    completion: "The Atlas interview is complete and Dev’s next handover is requested.",
  },
  {
    id: "release-atlas",
    role: "placement",
    act: 4,
    actionLabel: "Release Dev to Nova",
    title: "Approve the next opportunity",
    instruction: "Release Dev from Atlas so the company tracker can confirm the handover.",
    benefit: "Nova can prepare while Dev leaves Atlas.",
    completion: "Dev is ready for the Nova handover.",
  },
  {
    id: "handover-atlas",
    role: "company",
    companyScope: "atlas",
    act: 4,
    actionLabel: "Confirm Atlas handover",
    title: "Send Dev to Nova",
    instruction: "Confirm that Dev has left Atlas Systems for Nova Labs.",
    benefit: "Nova’s application starts automatically and the route is recorded.",
    completion: "Dev has been handed over and is now in transit to Nova Labs.",
  },
  {
    id: "arrive-nova",
    role: "floor",
    act: 4,
    actionLabel: "Confirm Nova arrival",
    title: "Get Dev to the second room",
    instruction: "Confirm Dev at Nova Labs before the rescheduled interview.",
    benefit: "Dev reaches the opportunity saved in Act 1.",
    completion: "Dev has arrived at Nova Labs.",
  },
  {
    id: "request-nova",
    role: "company",
    companyScope: "nova",
    act: 5,
    actionLabel: "Request Dev for Nova",
    title: "Call Dev into Nova",
    instruction: "Nova is ready. Request Dev from the floor queue.",
    benefit: "The second interview can begin on the protected schedule.",
    completion: "Nova Labs has requested Dev.",
  },
  {
    id: "approve-nova",
    role: "placement",
    act: 5,
    actionLabel: "Approve handoff to Nova",
    title: "Send Dev into Nova",
    instruction: "Coordinate Nova’s request and release Dev to the interview room.",
    benefit: "Dev reaches both opportunities in one placement day.",
    completion: "Dev is ready to interview with Nova Labs.",
  },
  {
    id: "run-nova-interview",
    role: "company",
    companyScope: "nova",
    act: 5,
    actionLabel: "Record Nova interview complete",
    title: "Complete the second interview",
    instruction: "Confirm the interview is complete and request Dev’s return to the placement office.",
    benefit: "Both interviews are complete with nothing missed.",
    completion: "The Nova interview is complete and an outcome can be recorded.",
  },
  {
    id: "release-nova",
    role: "placement",
    act: 5,
    actionLabel: "Release Dev from Nova",
    title: "Close the interview route",
    instruction: "Approve Dev’s release from the final company process.",
    benefit: "The final decision can be handled cleanly.",
    completion: "Dev is ready to return to the placement office.",
  },
  {
    id: "confirm-nova",
    role: "company",
    companyScope: "nova",
    act: 5,
    actionLabel: "Confirm Nova handover",
    title: "Return Dev to placement",
    instruction: "Confirm the final handover to the placement office.",
    benefit: "Every interview and handover is now recorded.",
    completion: "Dev’s company interviews and handovers are complete.",
  },
  {
    id: "record-placement",
    role: "placement",
    act: 6,
    actionLabel: "Record Dev’s placement",
    title: "Record the candidate’s choice",
    instruction: "Dev chooses Nova Labs. Record the placement and close the competing Atlas application.",
    benefit: "One clear outcome replaces competing active records.",
    completion: "Dev has been placed with Nova Labs.",
  },
  {
    id: "review-trace",
    role: "auditor",
    act: 6,
    actionLabel: "Review the complete trace",
    title: "Verify every handoff",
    instruction: "Review the role, time, and change recorded for the full journey.",
    benefit: "The university can explain exactly how the opportunity was protected.",
    completion: "The complete placement trace has been reviewed.",
  },
];

function candidateSeed(): Record<string, Candidate> {
  return {
    dev: {
      id: "dev",
      initials: "DM",
      name: "Dev Malhotra",
      program: "Mechanical Engineering",
      location: "Academic block",
      privateTag: "Priority outreach",
      accommodation: "Allow 10 minutes for lift transfer",
    },
    aarav: {
      id: "aarav",
      initials: "AK",
      name: "Aarav Khanna",
      program: "Computer Science",
      location: "Atlas interview room",
      privateTag: "Offer preference pending",
      accommodation: "No additional logistics",
    },
    mira: {
      id: "mira",
      initials: "MR",
      name: "Mira Rao",
      program: "Economics",
      location: "Nova reception",
      privateTag: "Placement office follow-up",
      accommodation: "Step-free entrance requested",
    },
    zoya: {
      id: "zoya",
      initials: "ZD",
      name: "Zoya D'Souza",
      program: "Design",
      location: "Control room",
      privateTag: "Cross-company conflict reviewed",
      accommodation: "No additional logistics",
    },
    isha: {
      id: "isha",
      initials: "IN",
      name: "Isha Nair",
      program: "Business Analytics",
      location: "Placement office",
      privateTag: "Candidate preference complete",
      accommodation: "No additional logistics",
    },
  };
}

function companySeed(): Record<CompanyId, Company> {
  return {
    atlas: { id: "atlas", code: "ATLAS", name: "Atlas Systems" },
    nova: { id: "nova", code: "NOVA", name: "Nova Labs" },
    river: { id: "river", code: "RIVER", name: "River & Co." },
  };
}

function applicationSeed(): Record<string, Application> {
  return {
    "dev-atlas": {
      id: "dev-atlas",
      candidateId: "dev",
      companyId: "atlas",
      status: "scheduled",
      time: "11:15",
      originalTime: "11:15",
      round: "Technical interview",
      room: "Room A1",
    },
    "dev-nova": {
      id: "dev-nova",
      candidateId: "dev",
      companyId: "nova",
      status: "scheduled",
      time: "11:20",
      originalTime: "11:20",
      alternateTime: "11:50",
      round: "Case interview",
      room: "Room B2",
    },
    "aarav-atlas": {
      id: "aarav-atlas",
      candidateId: "aarav",
      companyId: "atlas",
      status: "inside",
      time: "10:30",
      originalTime: "10:30",
      round: "Technical interview",
      room: "Room A2",
    },
    "mira-nova": {
      id: "mira-nova",
      candidateId: "mira",
      companyId: "nova",
      status: "arrived",
      time: "11:05",
      originalTime: "11:05",
      round: "Case interview",
      room: "Room B1",
    },
    "zoya-river": {
      id: "zoya-river",
      candidateId: "zoya",
      companyId: "river",
      status: "scheduled",
      time: "12:15",
      originalTime: "12:15",
      round: "Portfolio review",
      room: "Studio C",
    },
    "isha-nova": {
      id: "isha-nova",
      candidateId: "isha",
      companyId: "nova",
      status: "sent",
      time: "10:50",
      originalTime: "10:50",
      round: "Final interview",
      room: "Room B3",
    },
  };
}

export function createInitialSession(): DemoSession {
  return {
    world: {
      candidates: candidateSeed(),
      companies: companySeed(),
      applications: applicationSeed(),
      audit: [
        {
          id: "E3",
          minute: 642,
          actor: "Control room",
          message: "A clash was detected between Dev’s Atlas and Nova interviews.",
        },
        {
          id: "E2",
          minute: 638,
          actor: "Placement office",
          message: "Nova Labs offered Dev a safe alternative at 11:50.",
          companyId: "nova",
        },
        {
          id: "E1",
          minute: 630,
          actor: "System",
          message: "Dev was scheduled with Atlas Systems and Nova Labs.",
          system: true,
        },
      ],
      clockMinute: 645,
      clashResolved: false,
      interviewsCompleted: 0,
      preferenceResolved: false,
      placementCompanyId: null,
      traceReviewed: false,
    },
    activeRole: "control",
    companyScope: "atlas",
    selectedCandidateId: "dev",
    mode: "guided",
    completedStepCount: 0,
    announcement: "The mission is ready. Resolve Dev’s scheduling clash first.",
    activityExpanded: false,
  };
}
